'use client'

import { useState, useEffect, useRef } from 'react'
import { useRouter } from 'next/navigation'
import {
  InternshipSubject,
  InternshipTrack,
  INTERNSHIP_PHASE_LABELS,
  INTERNSHIP_QUESTIONS_PER_SUBJECT,
  getInternshipPhase,
  getInternshipSubjects,
  Question,
} from '@/types'
import QuestionCard from '@/components/assessment/QuestionCard'
import Button from '@/components/ui/Button'

const LOADING_FACTS = [
  'Did you know? This assessment uses adaptive technology — questions adjust to your level as you answer.',
  'Tip: For situational judgement questions, think about what a professional mentor would consider best practice.',
  'Fun fact: Domain knowledge questions test applied thinking, not memorisation — read each scenario carefully.',
  'Tip: The interest profile section has no right or wrong answers — answer honestly for the most accurate results.',
  'Did you know? Your readiness report is generated by AI that analyses your full performance across all four phases.',
  'Tip: Take your time — the 2-minute timer gives you plenty of space to think. Accuracy matters more than speed.',
  'Fun fact: Soft skills (workplace scenarios) are one of the strongest predictors of internship success.',
]

function LoadingQuestion() {
  const [factIndex, setFactIndex] = useState(0)
  const [fade, setFade] = useState(true)

  useEffect(() => {
    const timer = setInterval(() => {
      setFade(false)
      setTimeout(() => { setFactIndex((i) => (i + 1) % LOADING_FACTS.length); setFade(true) }, 400)
    }, 5000)
    return () => clearInterval(timer)
  }, [])

  return (
    <div className="min-h-screen bg-[#f5f5f7] flex items-center justify-center px-4">
      <div className="text-center space-y-6 max-w-sm">
        <div className="relative w-16 h-16 mx-auto">
          <div className="absolute inset-0 rounded-full border-4 border-[#e0e7ff]" />
          <div className="absolute inset-0 rounded-full border-4 border-[#4F46E5] border-t-transparent animate-spin" />
        </div>
        <div className="space-y-1.5">
          <p className="text-[#1d1d1f] font-semibold text-base">Preparing your next question</p>
          <p className="text-[#6e6e73] text-sm">AI is personalising your assessment in real time.</p>
        </div>
        <div
          className="bg-white border border-[#d2d2d7] rounded-2xl px-5 py-3.5 text-sm text-[#6e6e73] leading-relaxed transition-opacity duration-400"
          style={{ opacity: fade ? 1 : 0 }}
        >
          {LOADING_FACTS[factIndex]}
        </div>
      </div>
    </div>
  )
}

function WarmupCountdown({ count }: { count: number }) {
  return (
    <div className="min-h-screen bg-[#f5f5f7] flex items-center justify-center px-4">
      <div className="text-center space-y-6 max-w-xs">
        <div className="relative w-28 h-28 mx-auto">
          <svg className="w-28 h-28 -rotate-90 absolute inset-0" viewBox="0 0 112 112">
            <circle cx="56" cy="56" r="50" fill="none" stroke="#e0e7ff" strokeWidth="6" />
            <circle cx="56" cy="56" r="50" fill="none" stroke="#4F46E5" strokeWidth="6"
              strokeDasharray={`${2 * Math.PI * 50}`}
              strokeDashoffset={`${2 * Math.PI * 50 * (count / 4)}`}
              className="transition-all duration-700"
            />
          </svg>
          <div className="absolute inset-0 flex items-center justify-center">
            <span key={count} className="text-5xl font-bold text-[#4F46E5] animate-in zoom-in-50 duration-300">
              {count > 0 ? count : '🚀'}
            </span>
          </div>
        </div>
        <div className="space-y-1">
          <p className="text-lg font-semibold text-[#1d1d1f]">{count > 0 ? 'Get ready!' : "Let's go!"}</p>
          <p className="text-sm text-[#6e6e73]">Your internship assessment is about to begin.</p>
        </div>
      </div>
    </div>
  )
}

// ── Internship progress bar ────────────────────────────────────────────────────

const PHASE_ORDER = ['aptitude', 'domain', 'soft_skills', 'interest'] as const
const PHASE_DOTS = { aptitude: 2, domain: 1, soft_skills: 1, interest: 1 } // internal subject count per phase

function InternshipProgressBar({
  currentSubject,
  questionIndex,
  questionsForSubject,
  completedSubjects,
  track,
}: {
  currentSubject: InternshipSubject
  questionIndex: number
  questionsForSubject: number
  completedSubjects: InternshipSubject[]
  track: InternshipTrack
}) {
  const currentPhase = getInternshipPhase(currentSubject)
  const allSubjects = getInternshipSubjects(track)
  const completedPhases = new Set(completedSubjects.map(getInternshipPhase))
  // aptitude phase is complete only when both verbal + math are done
  if (completedSubjects.includes('aptitude_verbal') && completedSubjects.includes('aptitude_math')) {
    completedPhases.add('aptitude')
  }

  const totalQ = allSubjects.reduce((s, sub) => s + (INTERNSHIP_QUESTIONS_PER_SUBJECT[sub] ?? 0), 0)
  const doneQ = completedSubjects.reduce((s, sub) => s + (INTERNSHIP_QUESTIONS_PER_SUBJECT[sub] ?? 0), 0) + questionIndex
  const pct = Math.round((doneQ / totalQ) * 100)

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          {PHASE_ORDER.map((phase, i) => {
            const done = completedPhases.has(phase)
            const active = phase === currentPhase && !done
            return (
              <div key={phase} className="flex items-center gap-2">
                <div className={`flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-medium transition-all ${
                  done ? 'bg-emerald-100 text-emerald-700' : active ? 'bg-[#eef2ff] text-[#4F46E5]' : 'bg-[#f5f5f7] text-[#6e6e73]'
                }`}>
                  {done && <svg className="w-3 h-3" fill="none" viewBox="0 0 12 12" stroke="currentColor" strokeWidth={2.5}><polyline points="2 6 5 9 10 3" /></svg>}
                  {INTERNSHIP_PHASE_LABELS[phase]}
                </div>
                {i < PHASE_ORDER.length - 1 && <div className="w-3 h-px bg-[#d2d2d7]" />}
              </div>
            )
          })}
        </div>
        <span className="text-xs text-[#6e6e73] font-medium tabular-nums">{pct}%</span>
      </div>
      <div className="h-1.5 bg-[#f5f5f7] rounded-full overflow-hidden">
        <div
          className="h-full bg-[#4F46E5] rounded-full transition-all duration-500"
          style={{ width: `${pct}%` }}
        />
      </div>
      <p className="text-xs text-[#6e6e73]">
        {INTERNSHIP_PHASE_LABELS[currentPhase]} · Question {questionIndex + 1} of {questionsForSubject}
      </p>
    </div>
  )
}

// ── Types ──────────────────────────────────────────────────────────────────────

interface SessionState {
  current_subject: InternshipSubject
  subject_index: number
  question_index: number
  difficulty_level: number
  completed_subjects: InternshipSubject[]
}

type FetchResult =
  | { type: 'question'; question: Question; session: SessionState; track: InternshipTrack }
  | { type: 'break'; nextSubject: InternshipSubject; track: InternshipTrack }
  | { type: 'complete' }
  | { type: 'error'; message: string }

// ── Main component ─────────────────────────────────────────────────────────────

export default function InternshipClient({ assessmentId }: { assessmentId: string }) {
  const router = useRouter()

  type Phase = 'warmup' | 'loading' | 'question' | 'break' | 'error'
  const [phase, setPhase]             = useState<Phase>('warmup')
  const [warmupCount, setWarmupCount] = useState(4)
  const [question, setQuestion]       = useState<Question | null>(null)
  const [session, setSession]         = useState<SessionState | null>(null)
  const [track, setTrack]             = useState<InternshipTrack>('tech')
  const [breakSubject, setBreakSubject] = useState<InternshipSubject | null>(null)
  const [error, setError]             = useState('')

  const pendingRef = useRef<FetchResult | null>(null)

  function applyResult(result: FetchResult) {
    if (result.type === 'complete') {
      router.push(`/internship/assessment/${assessmentId}/complete`)
    } else if (result.type === 'error') {
      setError(result.message)
      setPhase('error')
    } else if (result.type === 'break') {
      setBreakSubject(result.nextSubject)
      setTrack(result.track)
      setPhase('break')
    } else {
      setQuestion(result.question)
      setSession(result.session)
      setTrack(result.track)
      setPhase('question')
    }
  }

  async function doFetch(retries = 2): Promise<FetchResult> {
    try {
      const res = await fetch(`/api/internship/${assessmentId}/question`)
      const data = await res.json()
      if (!res.ok) {
        const isOverloaded = typeof data.error === 'string' && data.error.includes('overloaded')
        if (isOverloaded && retries > 0) {
          await new Promise((r) => setTimeout(r, 3000))
          return doFetch(retries - 1)
        }
        return {
          type: 'error',
          message: isOverloaded
            ? 'Our AI is very busy right now. Please wait a moment and try again.'
            : data.error || 'Failed to load question',
        }
      }
      if (data.completed) return { type: 'complete' }
      if (data.subject_break) return { type: 'break', nextSubject: data.next_subject, track: data.track }
      return { type: 'question', question: data.question, session: data.session, track: data.track }
    } catch {
      return { type: 'error', message: 'Network error. Please try again.' }
    }
  }

  async function fetchNextQuestion() {
    setPhase('loading')
    setQuestion(null)
    setBreakSubject(null)
    const result = await doFetch()
    applyResult(result)
  }

  useEffect(() => {
    let countdownDone = false
    doFetch().then((result) => {
      if (countdownDone) applyResult(result)
      else pendingRef.current = result
    })
    let count = 4
    const interval = setInterval(() => {
      count -= 1
      setWarmupCount(count)
      if (count <= 0) {
        clearInterval(interval)
        countdownDone = true
        if (pendingRef.current) applyResult(pendingRef.current)
        else setPhase('loading')
      }
    }, 1000)
    return () => clearInterval(interval)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  // Prefetch next question in background after each question loads
  useEffect(() => {
    if (!question) return
    fetch(`/api/internship/${assessmentId}/prefetch`, { method: 'POST' }).catch(() => {})
  }, [question?.id, assessmentId])

  async function handleAnswer(selectedAnswer: string, timeTaken: number) {
    if (!question) return null
    const res = await fetch(`/api/internship/${assessmentId}/answer`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ question_id: question.id, selected_answer: selectedAnswer, time_taken_seconds: timeTaken }),
    })
    const data = await res.json()
    if (data.all_complete) {
      // Trigger complete endpoint before redirecting
      await fetch(`/api/internship/${assessmentId}/complete`, { method: 'POST' })
      router.push(`/internship/assessment/${assessmentId}/complete`)
      return null
    }
    return {
      isCorrect: data.is_correct as boolean,
      correctAnswer: data.correct_answer as string,
      explanation: (data.explanation ?? null) as string | null,
      selectedAnswer,
    }
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  if (phase === 'warmup') return <WarmupCountdown count={warmupCount} />
  if (phase === 'loading') return <LoadingQuestion />

  if (phase === 'error') {
    return (
      <div className="min-h-screen bg-[#f5f5f7] flex items-center justify-center">
        <div className="text-center space-y-4 max-w-sm px-4">
          <p className="text-red-600 text-sm">{error}</p>
          <Button onClick={fetchNextQuestion}>Try again</Button>
        </div>
      </div>
    )
  }

  if (phase === 'break' && breakSubject) {
    const nextPhase = getInternshipPhase(breakSubject)
    return (
      <div className="min-h-screen bg-[#f5f5f7] flex items-center justify-center px-4">
        <div className="w-full max-w-md bg-white rounded-3xl border border-[#d2d2d7] shadow-sm p-8 text-center space-y-6">
          <div className="w-16 h-16 bg-emerald-100 rounded-full flex items-center justify-center mx-auto">
            <svg className="w-8 h-8 text-emerald-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
          </div>
          <div>
            <h2 className="text-xl font-bold text-[#1d1d1f] mb-2 tracking-tight">Phase complete!</h2>
            <p className="text-[#6e6e73] text-sm">
              Great work. Take a moment before continuing to{' '}
              <strong className="text-[#1d1d1f]">{INTERNSHIP_PHASE_LABELS[nextPhase]}</strong>.
            </p>
          </div>
          <div className="bg-[#f5f5f7] rounded-2xl p-4 text-sm text-[#6e6e73]">
            Stretch, have some water, and come back when you&apos;re ready.
          </div>
          <Button className="w-full bg-[#4F46E5] hover:bg-[#4338CA] text-white" size="lg" onClick={fetchNextQuestion}>
            Continue to {INTERNSHIP_PHASE_LABELS[nextPhase]}
          </Button>
        </div>
      </div>
    )
  }

  if (!question || !session) return null

  const questionsForSubject = INTERNSHIP_QUESTIONS_PER_SUBJECT[session.current_subject] ?? 10

  return (
    <div className="min-h-screen bg-[#f5f5f7]">
      <div className="max-w-2xl mx-auto px-4 py-8 space-y-4">
        <div className="bg-white rounded-3xl border border-[#d2d2d7] p-5">
          <InternshipProgressBar
            currentSubject={session.current_subject}
            questionIndex={session.question_index}
            questionsForSubject={questionsForSubject}
            completedSubjects={session.completed_subjects}
            track={track}
          />
        </div>
        <div className="bg-white rounded-3xl border border-[#d2d2d7] p-6">
          <QuestionCard
            question={question}
            onAnswer={handleAnswer}
            onNext={fetchNextQuestion}
            questionNumber={session.question_index + 1}
            totalQuestions={questionsForSubject}
          />
        </div>
      </div>
    </div>
  )
}
