export const SUBJECTS = {
  english: {
    title: 'Free English Assessment for Children',
    headline: 'English',
    tagline: 'Comprehension, grammar, spelling and vocabulary — benchmarked internationally',
    description: 'Free adaptive English assessment for children aged 6–17. Covers reading comprehension, grammar, spelling, punctuation and vocabulary. Standardised scores.',
    color: 'bg-rose-50 text-rose-700 border-rose-100',
    accent: 'text-rose-600',
    skills: [
      { name: 'Reading comprehension', detail: 'Understanding and interpreting written passages across fiction and non-fiction genres' },
      { name: 'Grammar', detail: 'Parts of speech, sentence structure, tenses, and clause types' },
      { name: 'Spelling', detail: 'Common and complex spelling patterns, homophones, prefixes and suffixes' },
      { name: 'Punctuation', detail: 'Commas, apostrophes, speech marks, colons, and semicolons' },
      { name: 'Vocabulary', detail: 'Word meanings, synonyms, antonyms, and contextual usage' },
    ],
    benchmarks: ['UK National Curriculum KS1–KS4', 'Cambridge IGCSE English', 'PISA reading literacy', 'IB English Language & Literature'],
    ageGroups: [
      { range: 'Ages 6–7 (KS1)', focus: 'Phonics, simple sentences, basic punctuation' },
      { range: 'Ages 8–11 (KS2)', focus: 'Reading comprehension, paragraphing, complex punctuation' },
      { range: 'Ages 11–14 (KS3)', focus: 'Literary analysis, formal writing, advanced grammar' },
      { range: 'Ages 14–17 (KS4)', focus: 'Critical analysis, rhetoric, GCSE-level language skills' },
    ],
    sampleQuestions: [
      {
        type: 'Reading comprehension',
        question: 'The ancient temple was shrouded in mystery, its stones worn smooth by centuries of rain. What does "shrouded" most likely mean in this sentence?',
        options: ['A) lit up brightly', 'B) surrounded or hidden', 'C) recently constructed', 'D) carefully decorated'],
        answer: 'B — "Shrouded" means surrounded or hidden, as in covered by mist or secrecy.',
      },
      {
        type: 'Grammar',
        question: 'Choose the correctly punctuated sentence.',
        options: ["A) The children, who were tired went home early.", "B) The children, who were tired, went home early.", "C) The children who, were tired went home early.", "D) The children who were tired, went home early."],
        answer: "B — The non-restrictive clause 'who were tired' must be enclosed in commas on both sides.",
      },
      {
        type: 'Vocabulary',
        question: 'Which word is closest in meaning to "benevolent"?',
        options: ['A) hostile', 'B) cautious', 'C) kind', 'D) energetic'],
        answer: 'C — Benevolent means well-meaning and kind.',
      },
    ],
    prepTips: [
      'Read a mix of genres daily — fiction, news, and non-fiction. PISA research shows reading for pleasure is the single strongest predictor of reading scores.',
      'Learn the grammar terms: noun, verb, adjective, adverb, conjunction, clause. Most comprehension questions use them in their wording.',
      'Build vocabulary systematically: one new word per day, used in a sentence. Apps like Anki work well for spaced repetition.',
      'Practise spotting punctuation rules — apostrophes for possession vs. contraction are the most commonly tested.',
      'Time yourself on reading passages: 2 minutes to read, 1 minute per question. Speed matters at KS3 and above.',
    ],
    longTailKeywords: ['free English test for children UK', 'English comprehension test for kids', 'KS2 English assessment free', 'reading comprehension test children', 'free grammar test primary school UK', '11+ English practice questions free'],
  },
  maths: {
    title: 'Free Maths Assessment for Children',
    headline: 'Mathematics',
    tagline: 'Number, algebra, geometry and data handling — from KS1 to GCSE level',
    description: 'Free adaptive maths assessment for children aged 6–17. Covers number operations, algebra, geometry, fractions and data handling. Standardised scores.',
    color: 'bg-amber-50 text-amber-700 border-amber-100',
    accent: 'text-amber-600',
    skills: [
      { name: 'Number operations', detail: 'Addition, subtraction, multiplication, division, order of operations' },
      { name: 'Algebra', detail: 'Equations, expressions, sequences, functions, and simultaneous equations' },
      { name: 'Geometry', detail: 'Shape properties, angles, area, perimeter, volume, and transformations' },
      { name: 'Fractions & percentages', detail: 'Equivalent fractions, operations with fractions, decimals, and percentages' },
      { name: 'Data handling', detail: 'Mean, median, mode, probability, charts, and statistical interpretation' },
    ],
    benchmarks: ['UK National Curriculum KS1–KS4', 'PISA mathematical literacy', 'US Common Core Mathematics', 'IB Mathematics'],
    ageGroups: [
      { range: 'Ages 6–7 (KS1)', focus: 'Counting, basic addition and subtraction, simple shapes' },
      { range: 'Ages 8–11 (KS2)', focus: 'Times tables, fractions, written methods, basic algebra' },
      { range: 'Ages 11–14 (KS3)', focus: 'Algebra, ratio, geometry, statistics, negative numbers' },
      { range: 'Ages 14–17 (KS4)', focus: 'Quadratics, trigonometry, probability, GCSE-level problem solving' },
    ],
    sampleQuestions: [
      {
        type: 'Fractions',
        question: 'What is ¾ of 160?',
        options: ['A) 80', 'B) 100', 'C) 120', 'D) 140'],
        answer: 'C — ¾ × 160 = 120. Divide by 4 first (= 40), then multiply by 3.',
      },
      {
        type: 'Algebra',
        question: 'Solve for x: 3x + 7 = 22',
        options: ['A) x = 3', 'B) x = 5', 'C) x = 7', 'D) x = 9'],
        answer: 'B — Subtract 7 from both sides: 3x = 15. Divide by 3: x = 5.',
      },
      {
        type: 'Geometry',
        question: 'A rectangle has a length of 9 cm and a perimeter of 26 cm. What is its width?',
        options: ['A) 3 cm', 'B) 4 cm', 'C) 5 cm', 'D) 8 cm'],
        answer: 'B — Perimeter = 2(length + width). 26 = 2(9 + w), so 13 = 9 + w, giving w = 4 cm.',
      },
    ],
    prepTips: [
      'Secure the times tables up to 12×12 first — almost every maths topic from fractions to algebra runs faster with instant recall.',
      'Show all working, even on practice papers. Marks are often given for method, and errors are much easier to trace and correct.',
      'Target the specific topics where marks are lost most frequently at KS2: fractions, percentages, and word problems.',
      'Use past KS2 SAT papers (freely available on gov.uk) to practise under timed conditions — 45 minutes per paper.',
      'For 11+ preparation: the GL Assessment maths paper emphasises problem-solving and multi-step reasoning, not just calculation.',
    ],
    longTailKeywords: ['free maths test for children UK', 'KS2 maths assessment', 'free numeracy test for kids', 'primary school maths test online free', 'free 11+ maths practice questions', 'maths test for 10 year olds UK free'],
  },
  'verbal-reasoning': {
    title: 'Free Verbal Reasoning Test for Children',
    headline: 'Verbal Reasoning',
    tagline: 'Problem-solving with words — essential for 11+, grammar school, and independent school entry',
    description: 'Free adaptive verbal reasoning test for children aged 7–16. Covers word analogies, codes, classification and logic puzzles. Used in UK 11+ entrance exams.',
    color: 'bg-indigo-50 text-indigo-700 border-indigo-100',
    accent: 'text-indigo-600',
    skills: [
      { name: 'Word analogies', detail: 'Identifying relationships between pairs of words (e.g. hot : cold :: up : __)' },
      { name: 'Classification', detail: 'Identifying the odd word out from a group based on meaning or category' },
      { name: 'Word sequences', detail: 'Completing sequences of words following a logical pattern' },
      { name: 'Codes', detail: 'Decoding letter and number codes based on given examples' },
      { name: 'Logic and deduction', detail: 'Drawing conclusions from sets of statements' },
    ],
    benchmarks: ['GL Assessment 11+', 'CEM 11+ (Durham University)', 'Independent school entrance exams (ISEB)', 'Cognitive Abilities Test (CAT4)'],
    ageGroups: [
      { range: 'Ages 7–8', focus: 'Simple word relationships, basic analogies' },
      { range: 'Ages 9–10', focus: 'Word codes, classification, sequences' },
      { range: 'Ages 11–12', focus: 'Full 11+ verbal reasoning — analogies, codes, logic' },
      { range: 'Ages 13–16', focus: 'Advanced logic, abstract verbal reasoning, CAT4 level' },
    ],
    sampleQuestions: [
      {
        type: 'Word analogy',
        question: 'Hot is to Cold as Fast is to ___.',
        options: ['A) Speed', 'B) Slow', 'C) Run', 'D) Quick'],
        answer: 'B — The relationship is antonym (opposite). The opposite of Fast is Slow.',
      },
      {
        type: 'Classification (odd one out)',
        question: 'Which word does not belong? Apple · Banana · Carrot · Mango · Grape',
        options: ['A) Apple', 'B) Banana', 'C) Carrot', 'D) Mango'],
        answer: 'C — Carrot is a vegetable. All others are fruits.',
      },
      {
        type: 'Letter code',
        question: 'If CAT = DBU, what does DOG equal using the same code?',
        options: ['A) EPH', 'B) CNF', 'C) EPH', 'D) FQI'],
        answer: 'A — Each letter shifts one forward in the alphabet: D→E, O→P, G→H = EPH.',
      },
    ],
    prepTips: [
      'Practise one question type at a time before mixing them. There are 21 standard verbal reasoning question types — mastering each individually is faster than jumping between them.',
      'Wide reading builds the vocabulary that underpins analogy, classification, and odd-one-out questions. Aim for 20 minutes of reading per day.',
      'Bond Verbal Reasoning Assessment Papers (ages 9–10+) are the closest match to GL Assessment 11+ format. Work through one paper per week, then review errors carefully.',
      'For letter codes: write the alphabet with numbers 1–26 beneath it. Most code questions use simple shifts (A+1=B, A+2=C, etc.).',
      'Timed practice matters: the GL Assessment gives approximately 50 seconds per verbal reasoning question. Practise answering quickly and moving on when stuck.',
    ],
    longTailKeywords: ['free verbal reasoning test 11+ UK', 'verbal reasoning practice test children', 'free 11+ verbal reasoning', 'GL assessment verbal reasoning practice', 'verbal reasoning sample questions KS2', 'how to prepare for 11+ verbal reasoning'],
  },
  'non-verbal-reasoning': {
    title: 'Free Non-Verbal Reasoning Test for Children',
    headline: 'Non-Verbal Reasoning',
    tagline: 'Pattern recognition, spatial reasoning, and abstract thinking — language-independent',
    description: 'Free adaptive non-verbal reasoning test for children aged 7–16, covering pattern recognition, matrix reasoning, sequences and spatial reasoning.',
    color: 'bg-emerald-50 text-emerald-700 border-emerald-100',
    accent: 'text-emerald-600',
    skills: [
      { name: 'Pattern completion', detail: 'Identifying and continuing visual patterns using shapes and symbols' },
      { name: 'Matrix reasoning', detail: 'Completing a 3×3 grid of shapes where one piece is missing' },
      { name: 'Sequences', detail: 'Identifying the next shape in a visual sequence' },
      { name: 'Spatial reasoning', detail: 'Mental rotation and folding of 2D and 3D shapes' },
      { name: 'Figure series', detail: 'Identifying which shape or figure does not fit a series' },
    ],
    benchmarks: ['GL Assessment 11+', 'Cognitive Abilities Test (CAT4)', 'ISEB Common Pre-Test', 'Cognitive Abilities Test (NFER)'],
    ageGroups: [
      { range: 'Ages 7–8', focus: 'Simple pattern matching, basic shape sequences' },
      { range: 'Ages 9–10', focus: 'Matrix puzzles, rotation, figure series' },
      { range: 'Ages 11–12', focus: 'Full 11+ non-verbal reasoning standard' },
      { range: 'Ages 13–16', focus: 'Advanced spatial reasoning and abstract matrices (CAT4 level)' },
    ],
    sampleQuestions: [
      {
        type: 'Figure series',
        question: 'A sequence shows a square containing 1 dot, then 2 dots, then 3 dots. What comes next?',
        options: ['A) A square with 4 dots', 'B) A circle with 3 dots', 'C) A square with 5 dots', 'D) An empty square'],
        answer: 'A — The pattern adds one dot per step, and the shape (square) stays constant.',
      },
      {
        type: 'Matrix reasoning',
        question: 'A 3×3 grid shows large shapes in row 1, medium shapes in row 2, and small shapes in row 3. Columns show circle, triangle, square. The bottom-right cell is missing. What goes there?',
        options: ['A) A large square', 'B) A small triangle', 'C) A small square', 'D) A medium circle'],
        answer: 'C — Row 3 = small shapes. Column 3 = squares. Therefore: small square.',
      },
      {
        type: 'Spatial reasoning',
        question: 'A flat cross-shaped net is folded into a cube. Which face will be opposite the top face?',
        options: ['A) The face directly below it in the net', 'B) The face directly above it in the net', 'C) The face two positions below it', 'D) Any face — it is random'],
        answer: 'C — On a standard cross net, the face opposite the top is found two positions below in the vertical column.',
      },
    ],
    prepTips: [
      'Non-verbal reasoning is highly practice-responsive — unlike verbal or maths, children often show rapid improvement after targeted practice because the question types are finite.',
      'Bond Non-Verbal Reasoning Assessment Papers and CGP NVR books are the most widely used. Start with the 9–10 age bracket regardless of your child\'s actual age to build confidence.',
      'Practise paper folding physically: take a piece of A4, fold it, and predict where holes will appear when unfolded. This builds the spatial intuition that matrix and rotation questions require.',
      'For matrix questions: always check both the row pattern AND the column pattern. The correct answer must satisfy both simultaneously.',
      'Timed practice is critical — aim for 45–50 seconds per question. Many children know the answer but run out of time because they are not accustomed to the pace.',
    ],
    longTailKeywords: ['free non-verbal reasoning test children', '11+ non-verbal reasoning practice', 'spatial reasoning test kids UK', 'matrix reasoning test free children', 'how to prepare for 11+ non-verbal reasoning', 'GL assessment non-verbal reasoning sample questions'],
  },
} as const

export type Slug = keyof typeof SUBJECTS
